### ISSUE TITLE
Styling footer

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/alinka-website#29]
- compare with an example in Figma
- add 'Code for Poznań' logo -> logo for the dark background (svg) - put it on the left side of the footer
- put smaller social-media logos on the right side of the footer
- delete 'Pomóż Alince' 
- delete 'O Nas'
- logo CfP should direct to CfP website

**Comment by martabakaj** [comment]
Hey, I will be work on it :)

**Comment by martabakaj** [comment]
Hi, I change all where I had comments and I fixed conflikts. 
I shuld do somthing more or we can add it to master? :D (If answer is" Yes we can add it to master" Who should do it?". 
I will be grateful for the hint

**Comment by magul** [comment]
I believe it's waiting for @Bosmanfrx and @agatakozinska approvals, as they asked for some changes.

**Comment by magul** [comment]
Can you also @martabakaj back-merge master to your branch? It looks that it contains multiple files, that are already in `master` branch :/
